#!/usr/bin/env php
<?php

use Gacela\Framework\Bootstrap\GacelaConfig;
use Gacela\Framework\Gacela;
use PhpLightning\Console\Infrastructure\ConsoleBootstrap;

$cwd = (string)getcwd();
if (!file_exists($autoloadPath = $cwd . '/vendor/autoload.php')) {
    exit("Cannot load composer's autoload file: " . $autoloadPath);
}

require $autoloadPath;

Gacela::bootstrap(__DIR__, GacelaConfig::withPhpConfigDefault());

$bootstrap = new ConsoleBootstrap();
$bootstrap->run();
