#!/usr/bin/env php
<?php

use Gacela\Framework\Gacela;
use PhpLightning\Console\Infrastructure\ConsoleBootstrap;
use PhpLightning\Lightning;

$cwd = (string)getcwd();
if (!file_exists($autoloadPath = $cwd . '/vendor/autoload.php')) {
    exit("Cannot load composer's autoload file: " . $autoloadPath);
}

require $autoloadPath;

Gacela::bootstrap($cwd, Lightning::configFn());

$bootstrap = new ConsoleBootstrap();
$bootstrap->run();
